"""Core module for Pahang CLI."""

from src.core.contract import ContractScope
from src.core.normalizers import (
    extract_background_temperature,
    format_busbar_position,
    format_cbm_reading,
    format_date_cbm,
    format_date_front_page,
    format_db_int,
    format_heater_amp,
    format_humidity_str,
    format_iso8601,
    format_load_amp,
    format_month_folder,
    format_temperature_float,
    format_testsheet_time,
    normalize_date_str,
    normalize_fl_erms,
    normalize_for_csv,
    normalize_for_excel,
    normalize_for_report,
    normalize_us_characteristic,
    parse_background_temp,
    parse_battery_details,
)
from src.core.topology import (
    BayRole,
    BoardClassification,
    SwitchgearArchetype,
    SwitchgearTopologyEngine,
    VoltageClass,
    classify_bay_role,
    classify_voltage_rating,
    eval_pt_gate,
    eval_secondary_gate,
    extract_model_from_manufacturer,
    resolve_overview_compartments,
    resolve_panel_compartments,
    resolve_switchgear_archetype,
)


__all__ = [
    "BayRole",
    "BoardClassification",
    "ContractScope",
    "SwitchgearArchetype",
    "SwitchgearTopologyEngine",
    "VoltageClass",
    "classify_bay_role",
    "classify_voltage_rating",
    "eval_pt_gate",
    "eval_secondary_gate",
    "extract_background_temperature",
    "extract_model_from_manufacturer",
    "format_busbar_position",
    "format_cbm_reading",
    "format_date_cbm",
    "format_date_front_page",
    "format_db_int",
    "format_heater_amp",
    "format_humidity_str",
    "format_iso8601",
    "format_load_amp",
    "format_month_folder",
    "format_temperature_float",
    "format_testsheet_time",
    "normalize_date_str",
    "normalize_fl_erms",
    "normalize_for_csv",
    "normalize_for_excel",
    "normalize_for_report",
    "normalize_us_characteristic",
    "parse_background_temp",
    "parse_battery_details",
    "resolve_overview_compartments",
    "resolve_panel_compartments",
    "resolve_switchgear_archetype",
]


